sage tabuSearch.sagews grafo2teste_4events.txt
sage tabuSearch.sagews grafo3teste_6events.txt
sage tabuSearch.sagews grafo4teste_8events.txt
sage tabuSearch.sagews grafo5teste_10events.txt
sage tabuSearch.sagews grafo6teste_12events.txt
sage tabuSearch.sagews grafo7teste_14events.txt
sage tabuSearch.sagews grafo8teste_16events.txt
sage tabuSearch.sagews grafo9teste_18events.txt
sage tabuSearch.sagews grafo10teste_20events.txt
sage tabuSearch.sagews grafo11teste_22events.txt
sage tabuSearch.sagews grafo12teste_24events.txt
sage tabuSearch.sagews grafo13teste_26events.txt
sage tabuSearch.sagews grafo14teste_28events.txt
sage tabuSearch.sagews grafo15teste_30events.txt
sage tabuSearch.sagews grafo16teste_32events.txt
sage tabuSearch.sagews grafo17teste_34events.txt
sage tabuSearch.sagews grafo18teste_36events.txt
sage tabuSearch.sagews grafo19teste_38events.txt
sage tabuSearch.sagews grafo20teste_40events.txt
sage tabuSearch.sagews grafo21teste_42events.txt
sage tabuSearch.sagews grafo22teste_44events.txt
sage tabuSearch.sagews grafo23teste_46events.txt
sage tabuSearch.sagews grafo24teste_48events.txt
sage tabuSearch.sagews grafo25teste_50events.txt
sage tabuSearch.sagews grafo26teste_52events.txt
sage tabuSearch.sagews grafo27teste_54events.txt
sage tabuSearch.sagews grafo28teste_56events.txt
sage tabuSearch.sagews grafo29teste_58events.txt
sage tabuSearch.sagews grafo30teste_60events.txt
sage tabuSearch.sagews grafo31teste_62events.txt
sage tabuSearch.sagews grafo32teste_64events.txt
sage tabuSearch.sagews grafo33teste_66events.txt
sage tabuSearch.sagews grafo34teste_68events.txt
sage tabuSearch.sagews grafo35teste_70events.txt
sage tabuSearch.sagews grafo36teste_72events.txt
sage tabuSearch.sagews grafo37teste_74events.txt
sage tabuSearch.sagews grafo38teste_76events.txt
sage tabuSearch.sagews grafo39teste_78events.txt
sage tabuSearch.sagews grafo40teste_80events.txt
sage tabuSearch.sagews grafo41teste_82events.txt
sage tabuSearch.sagews grafo42teste_84events.txt
sage tabuSearch.sagews grafo43teste_86events.txt
sage tabuSearch.sagews grafo44teste_88events.txt
sage tabuSearch.sagews grafo45teste_90events.txt
sage tabuSearch.sagews grafo46teste_92events.txt
sage tabuSearch.sagews grafo47teste_94events.txt
sage tabuSearch.sagews grafo48teste_96events.txt
sage tabuSearch.sagews grafo49teste_98events.txt
sage tabuSearch.sagews grafo50teste_100events.txt
sage tabuSearch.sagews grafo51teste_102events.txt
sage tabuSearch.sagews grafo52teste_104events.txt
sage tabuSearch.sagews grafo53teste_106events.txt
sage tabuSearch.sagews grafo54teste_108events.txt
sage tabuSearch.sagews grafo55teste_110events.txt
sage tabuSearch.sagews grafo56teste_112events.txt
sage tabuSearch.sagews grafo57teste_114events.txt
sage tabuSearch.sagews grafo58teste_116events.txt
sage tabuSearch.sagews grafo59teste_118events.txt
sage tabuSearch.sagews grafo60teste_120events.txt
sage tabuSearch.sagews grafo61teste_122events.txt
sage tabuSearch.sagews grafo62teste_124events.txt
sage tabuSearch.sagews grafo63teste_126events.txt
sage tabuSearch.sagews grafo64teste_128events.txt
sage tabuSearch.sagews grafo65teste_130events.txt
sage tabuSearch.sagews grafo66teste_132events.txt
sage tabuSearch.sagews grafo67teste_134events.txt
sage tabuSearch.sagews grafo68teste_136events.txt
sage tabuSearch.sagews grafo69teste_138events.txt
sage tabuSearch.sagews grafo70teste_140events.txt
sage tabuSearch.sagews grafo71teste_142events.txt
sage tabuSearch.sagews grafo72teste_144events.txt
sage tabuSearch.sagews grafo73teste_146events.txt
sage tabuSearch.sagews grafo74teste_148events.txt
sage tabuSearch.sagews grafo75teste_150events.txt
sage tabuSearch.sagews grafo76teste_152events.txt
sage tabuSearch.sagews grafo77teste_154events.txt
sage tabuSearch.sagews grafo78teste_156events.txt
sage tabuSearch.sagews grafo79teste_158events.txt
sage tabuSearch.sagews grafo80teste_160events.txt
sage tabuSearch.sagews grafo81teste_162events.txt
sage tabuSearch.sagews grafo82teste_164events.txt
sage tabuSearch.sagews grafo83teste_166events.txt
sage tabuSearch.sagews grafo84teste_168events.txt
sage tabuSearch.sagews grafo85teste_170events.txt
sage tabuSearch.sagews grafo86teste_172events.txt
sage tabuSearch.sagews grafo87teste_174events.txt
sage tabuSearch.sagews grafo88teste_176events.txt
sage tabuSearch.sagews grafo89teste_178events.txt
sage tabuSearch.sagews grafo90teste_180events.txt
sage tabuSearch.sagews grafo91teste_182events.txt
sage tabuSearch.sagews grafo92teste_184events.txt
sage tabuSearch.sagews grafo93teste_186events.txt
sage tabuSearch.sagews grafo94teste_188events.txt
sage tabuSearch.sagews grafo95teste_190events.txt
sage tabuSearch.sagews grafo96teste_192events.txt
sage tabuSearch.sagews grafo97teste_194events.txt
sage tabuSearch.sagews grafo98teste_196events.txt
sage tabuSearch.sagews grafo99teste_198events.txt
sage tabuSearch.sagews grafo100teste_200events.txt
